### ISSUE TITLE
helpful error message if artefact is misspecified (missing 'type')

### ISSUE THREAD

**Issue by jeffeaton** [vimc/orderly#168]
It would be helpful to get an error message with more guidance if I forget to specify the artefact "type".

Simplified example of my wrong `orderly.yml`:

```
script: survey.R

artefacts:
  - survey_individuals.csv
```

The results for `orderly_run()` was:

```
> orderly::orderly_run("data-survey")
[ name       ]  data-survey
Error in vapply(X, FUN, character(1), ...) : values must be length 1,
 but FUN(X[[1]]) result is length 0
> 
```

This is entirely user error, but it took me a long time head scratching what I had done wrong that was giving me that error.

Thanks,
Jeff

**Comment by richfitz** [comment]
please see #175 for a fix
