### ISSUE TITLE
document that orderly_develop_start() also loads sources and packages

### ISSUE THREAD

**Issue by jeffeaton** [vimc/orderly#169]
I was hoping that `orderly_deveop_start()` would also load my packages and sources so that I am all ready to go in my session once I run it, which I think it does, which is great.

I couldn't find this clearly stated in the documentation `?orderly_develop_start` or in the `orderly` getting started vignette, and so had to do some testing to confirm it was loading those.

Suggestion to add this clearly in the documentation that it will do this bit for you.

Thanks,
Jeff

**Comment by jeffeaton** [comment]
Another comment on `orderly_develop_start()`: it would be nice to be able to execute this without specifying an artefact yet as I might only think of the artefacts I need as I develop the script.

```
> orderly::orderly_develop_start()
[ name       ]  fit-model
Error in recipe_read_check_artefacts(info$artefacts, filename, path) : 
  At least one artefact required
```

Not sure the consequences of allowing this under the hood. It's easy enough to put a 'dummy' file in for artefact if allowing no artefacts at this stage is problematic.

**Comment by richfitz** [comment]
This was something I was wondering about too, yes, thanks
