### ISSUE TITLE
add function to add resource to a report

### ISSUE THREAD

**Issue by jeffeaton** [vimc/orderly#171]
A function to automate the process of adding a resource to a report would be helpful, similar to `usethis::use_*` functionality. It would do the following:

- copying a file into the `src/<report>` directory (possibly with options to put it elsewhere as appropriate).
- add the file to `orderly.yml`.

Thanks,
Jeff

**Comment by richfitz** [comment]
Funnily enough, this is on my radar.  It's our VIMC-3503 and will follow on from the work we recently merged from VIMC-3404/#160
