### ISSUE TITLE
allow subdirectories in src/

### ISSUE THREAD

**Issue by jeffeaton** [vimc/orderly#172]
It would be nice to be able to organize the `src/` directory into subdirectories for tasks. I don't know what sorts of risk or consequences this might have, but if it is feasible it would help with organising a project.

I wasn't sure if it might already be supported, so I tested it and ran into an error from `file.copy()`:
```
> orderly::orderly_new("data/programme")
Error in file_copy(template, dest_yml) : Error copying files
In addition: Warning messages:
1: In dir.create(dest) :
  cannot create dir '/Users/jeff/Dropbox/Documents/Code/R/naomi-orderly-example/src/data/programme', reason 'No such file or directory'
2: In file.create(to[okay]) :
  cannot create file '/Users/jeff/Dropbox/Documents/Code/R/naomi-orderly-example/src/data/programme/orderly.yml', reason 'No such file or directory'
```
I manually created the subdirectory and tried again, and that worked to create the orderly task:
```
> dir.create("data")  # wd is src/
> orderly::orderly_new("data/programme")
Created report at '/Users/jeff/Dropbox/Documents/Code/R/naomi-orderly-example/src/data/programme'
Edit the file 'orderly.yml' within this directory
```

But then after setting up my `orderly.yml`, I was not able to go further because indeed it does expect `name` to be a single directory:
```
> orderly::orderly_develop_start()
Error in orderly_develop_location(name, root, locate) : 
  Unexpected working directory - expected src/<name>
```

Thanks,
Jeff

**Comment by richfitz** [comment]
I'm not going to support subdirectories as this idea is too baked into the system (and has been from the start), but you can get most of that with a sensible naming system.

```
src/project1-task1-subtask
src/project1-task2-another-subtask
src/project2-etc
```

We will also support some concepts of tags in the web interface soon at least.

**Comment by jeffeaton** [comment]
Great on the tags. Something I was thinking about that would be nice was to be able to tag something that could be referred to as an identifier in `depends: id:` other than `latest`.  The tag could be updated with different report IDs.  Is that similar to what you're doing or different?

**Comment by richfitz** [comment]
We are talking about tags now.  Not sure how they will feed into being useable in the depends, but we'll see

**Comment by richfitz** [comment]
I am going to close this because I think it will cause too many problems
