### ISSUE TITLE
Build theoretical dependency graphs from draft/

### ISSUE THREAD

**Issue by bjeffrey92** [vimc/orderly#196]
Whilst working on a project it would be good to identify inefficiencies related to the workflow as early as possible. Therefore, it would be useful if there was a function akin to `orderly::orderly_graph()` that would produce the dependency graph for a given task without having to commit the reports, i.e. just using the `draft/` directory.

**Comment by richfitz** [comment]
There are two things here I think - as soon as we use `draft` we're using realised reports.  Is that also useful?  Or is what you're looking for just going through the current set of orderly.yml files?  Mixing the two approaches will be hard, but agree that a pure-orderly.yml version would be very useful

**Comment by richfitz** [comment]
logged as VIMC-3610 on youtrack

**Comment by bjeffrey92** [comment]
I originally thought that going through the ordely.yml files would be useful but I stopped short of suggesting this because presumably any errors in the orderly.yml (for example if it has been edited and the task hasn't been run to check it still works) will then be reflected in the graph. Would probably still be useful though if it checked that the task had been run since the orderly.yml was last edited?

**Comment by r-ash** [comment]
You can now build a graph from `orderly.yml` files, e.g. `orderly::orderly_graph("report-name", use = "src")` see #221
